import type { IEntityMetadata } from '../types';
import { OperationType } from '../types/base/entity-types';

/**
 * List of available Autotask API entities
 * This includes all endpoints that can be accessed through the Autotask REST API
 */
export const AUTOTASK_ENTITIES: IEntityMetadata[] = [
	// BillingCode entity (read-only)
	{ name: 'BillingCode', operations: { [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'BillingItems', operations: { [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'Company', operations: { [OperationType.CREATE]: 'self', [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'self', [OperationType.COUNT]: 'self' }, supportsWebhookCallouts: true },
	{ name: 'CompanyAlert', operations: { [OperationType.CREATE]: 'self', [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'CompanyAttachment', childOf: 'Company', subname: 'Attachment', isAttachment: true, operations: { [OperationType.CREATE]: 'parent', [OperationType.DELETE]: 'parent' } },
	{ name: 'CompanyNote', childOf: 'Company', subname: 'Notes', parentIdField: 'companyID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'CompanyNoteAttachment', childOf: 'CompanyNote', subname: 'Attachment', parentChain: ['Company', 'CompanyNote'], isAttachment: true, operations: { [OperationType.CREATE]: 'parent', [OperationType.DELETE]: 'parent' } },
	{ name: 'CompanyWebhook', childOf: 'Company', subname: 'Webhook', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.DELETE]: 'parent' } },
	{ name: 'CompanyWebhookExcludedResource', childOf: 'CompanyWebhook', subname: 'ExcludedResource', parentChain: ['Company', 'CompanyWebhook'], operations: { [OperationType.CREATE]: 'parent', [OperationType.DELETE]: 'parent' } },
	{ name: 'CompanyWebhookField', childOf: 'CompanyWebhook', subname: 'Field', parentChain: ['Company', 'CompanyWebhook'], operations: { [OperationType.CREATE]: 'parent', [OperationType.DELETE]: 'parent' } },
	{ name: 'CompanyWebhookUdfField', childOf: 'CompanyWebhook', subname: 'UdfField', parentChain: ['Company', 'CompanyWebhook'], operations: { [OperationType.CREATE]: 'parent', [OperationType.DELETE]: 'parent' } },
	{ name: 'CompanySiteConfigurations', childOf: 'Company', subname: 'SiteConfigurations', parentIdField: 'companyID', operations: { [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' }, hasUserDefinedFields: true },
	// ConfigurationItem entity with webhook support flag
	{ name: 'ConfigurationItem', operations: { [OperationType.CREATE]: 'self', [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' }, hasUserDefinedFields: true, supportsWebhookCallouts: true },
	{ name: 'ConfigurationItemWebhook', childOf: 'ConfigurationItem', subname: 'Webhook', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.DELETE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ConfigurationItemWebhookExcludedResource', childOf: 'ConfigurationItemWebhook', subname: 'ExcludedResource', parentChain: ['ConfigurationItem', 'ConfigurationItemWebhook'], operations: { [OperationType.CREATE]: 'parent', [OperationType.DELETE]: 'parent' } },
	{ name: 'ConfigurationItemWebhookField', childOf: 'ConfigurationItemWebhook', subname: 'Field', parentChain: ['ConfigurationItem', 'ConfigurationItemWebhook'], operations: { [OperationType.CREATE]: 'parent', [OperationType.DELETE]: 'parent' } },
	{ name: 'ConfigurationItemWebhookUdfField', childOf: 'ConfigurationItemWebhook', subname: 'UdfField', parentChain: ['ConfigurationItem', 'ConfigurationItemWebhook'], operations: { [OperationType.CREATE]: 'parent', [OperationType.DELETE]: 'parent' } },
	{ name: 'ConfigurationItemCategory', operations: { [OperationType.CREATE]: 'self', [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ConfigurationItemCategoryUdfAssociation', childOf: 'ConfigurationItemCategory', subname: 'UdfAssociations', parentIdField: 'configurationItemCategoryID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self', [OperationType.DELETE]: 'parent' } },
	{ name: 'ConfigurationItemType', operations: { [OperationType.CREATE]: 'self', [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ConfigurationItemNote', childOf: 'ConfigurationItem', subname: 'Notes', parentIdField: 'configurationItemID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ConfigurationItemRelatedItem', childOf: 'ConfigurationItem', subname: 'RelatedItems', parentIdField: 'configurationItemID', operations: { [OperationType.CREATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'parent', [OperationType.COUNT]: 'self' } },
	{ name: 'ConfigurationItemDnsRecord', childOf: 'ConfigurationItem', subname: 'DnsRecords', parentIdField: 'configurationItemID', operations: { [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'parent', [OperationType.COUNT]: 'self' } },
	{ name: 'ConfigurationItemBillingProductAssociations', childOf: 'ConfigurationItem', subname: 'BillingProductAssociations', parentIdField: 'configurationItemID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'parent', [OperationType.COUNT]: 'self' } },
	{ name: 'ConfigurationItemSslSubjectAlternativeName', childOf: 'ConfigurationItem', subname: 'SslSubjectAlternativeNames', parentIdField: 'configurationItemID', operations: { [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'parent', [OperationType.COUNT]: 'self' } },
	{ name: 'Contact', childOf: 'Company', subname: 'Contact', parentIdField: 'companyID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' }, supportsWebhookCallouts: true },
	{ name: 'ContactGroups', operations: { [OperationType.CREATE]: 'self', [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ContactGroupContacts', operations: { [OperationType.CREATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ContactWebhook', childOf: 'Contact', subname: 'Webhook', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.DELETE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ContactWebhookExcludedResource', childOf: 'ContactWebhook', subname: 'ExcludedResource', parentChain: ['Company', 'Contact', 'ContactWebhook'], operations: { [OperationType.CREATE]: 'parent', [OperationType.DELETE]: 'parent' } },
	{ name: 'ContactWebhookField', childOf: 'ContactWebhook', subname: 'Field', parentChain: ['Company', 'Contact', 'ContactWebhook'], operations: { [OperationType.CREATE]: 'parent', [OperationType.DELETE]: 'parent' } },
	{ name: 'ContactWebhookUdfField', childOf: 'ContactWebhook', subname: 'UdfField', parentChain: ['Company', 'Contact', 'ContactWebhook'], operations: { [OperationType.CREATE]: 'parent', [OperationType.DELETE]: 'parent' } },
	{ name: 'CompanyLocation', childOf: 'Company', subname: 'Locations', parentIdField: 'companyID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'parent', [OperationType.COUNT]: 'self' } },
	{ name: 'Contract', operations: { [OperationType.CREATE]: 'self', [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ContractBillingRule', childOf: 'Contract', subname: 'BillingRules', parentIdField: 'contractID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'parent', [OperationType.COUNT]: 'self' } },
	{ name: 'ContractCharge', childOf: 'Contract', subname: 'Charges', parentIdField: 'contractID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'parent', [OperationType.COUNT]: 'self' } },
	{ name: 'ContractExclusionBillingCode', childOf: 'Contract', subname: 'ExclusionBillingCodes', parentIdField: 'contractID', operations: { [OperationType.CREATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'parent', [OperationType.COUNT]: 'self' } },
	{ name: 'ContractMilestone', childOf: 'Contract', subname: 'Milestones', parentIdField: 'contractID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ContractNote', childOf: 'Contract', subname: 'Notes', parentIdField: 'contractID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ContractService', childOf: 'Contract', subname: 'Services', parentIdField: 'contractID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ContractTicketPurchases', childOf: 'Contract', subname: 'TicketPurchases', parentIdField: 'contractID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ContractServiceAdjustment', childOf: 'Contract', subname: 'ServiceAdjustments', parentIdField: 'contractID', operations: { [OperationType.CREATE]: 'parent' } },
	{ name: 'ContractServiceBundleAdjustment', childOf: 'Contract', subname: 'ServiceBundleAdjustments', parentIdField: 'contractID', operations: { [OperationType.CREATE]: 'parent' } },
	{ name: 'ContractServiceBundle', childOf: 'Contract', subname: 'ServiceBundles', parentIdField: 'contractID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ContractServiceBundleUnit', childOf: 'Contract', subname: 'ServiceBundleUnits', parentIdField: 'contractID', operations: { [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ContractServiceUnit', childOf: 'Contract', subname: 'ServiceUnits', parentIdField: 'contractID', operations: { [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ContractBlock', childOf: 'Contract', subname: 'Blocks', parentIdField: 'contractID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ContractBlockHourFactor', childOf: 'Contract', subname: 'BlockHourFactors', parentIdField: 'contractID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ContractRate', childOf: 'Contract', subname: 'Rates', parentIdField: 'contractID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ContractRoleCosts', childOf: 'Contract', subname: 'RoleCosts', parentIdField: 'contractID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ContractRetainers', childOf: 'Contract', subname: 'Retainers', parentIdField: 'contractID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ContractExclusionRoles', childOf: 'Contract', subname: 'ExclusionRoles', parentIdField: 'contractID', operations: { [OperationType.CREATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'parent', [OperationType.COUNT]: 'self' } },
	{ name: 'ContractExclusionSets', operations: { [OperationType.CREATE]: 'self', [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ContractExclusionSetExcludedRoles', childOf: 'ContractExclusionSets', subname: 'ExcludedRoles', parentIdField: 'contractExclusionSetID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'parent', [OperationType.COUNT]: 'self' } },
	{ name: 'ContractExclusionSetExcludedWorkTypes', childOf: 'ContractExclusionSets', subname: 'ExcludedWorkTypes', parentIdField: 'contractExclusionSetID', operations: { [OperationType.CREATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'parent', [OperationType.COUNT]: 'self' } },
	{ name: 'Country', operations: { [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self', [OperationType.UPDATE]: 'self' } },
	{ name: 'DomainRegistrar', operations: { [OperationType.CREATE]: 'self', [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'HolidaySet', operations: { [OperationType.CREATE]: 'self', [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'Holiday', childOf: 'HolidaySet', subname: 'Holidays', parentIdField: 'holidaySetID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'parent', [OperationType.COUNT]: 'self' } },
	{ name: 'Invoice', operations: { [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'NotificationHistory', operations: { [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' }, noPluralize: true },
	{ name: 'Opportunity', operations: { [OperationType.CREATE]: 'self', [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'Product', operations: { [OperationType.CREATE]: 'self', [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' }, hasUserDefinedFields: true },
	{ name: 'ProductVendors', childOf: 'Product', subname: 'Vendors', parentIdField: 'productID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'Project', operations: { [OperationType.CREATE]: 'self', [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' }, parentIdField: 'companyID' },
	{ name: 'ProjectNote', childOf: 'Project', subname: 'Notes', parentIdField: 'projectID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ProjectCharge', childOf: 'Project', subname: 'Charges', parentIdField: 'projectID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'parent', [OperationType.COUNT]: 'self' } },
	{ name: 'Phase', childOf: 'Project', subname: 'Phases', parentIdField: 'projectID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'Quote', operations: { [OperationType.CREATE]: 'self', [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'QuoteItem', childOf: 'Quote', subname: 'Items', parentIdField: 'quoteID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'parent', [OperationType.COUNT]: 'self' } },
	{ name: 'QuoteLocation', childOf: 'Quote', subname: 'Locations', parentIdField: 'quoteID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'QuoteTemplate', operations: { [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'Resource', operations: { [OperationType.QUERY]: 'self', [OperationType.READ]: 'self', [OperationType.COUNT]: 'self', [OperationType.UPDATE]: 'self' } },
	{ name: 'ResourceRole', childOf: 'Resource', subname: 'Roles', parentIdField: 'resourceID', operations: { [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'Role', operations: { [OperationType.CREATE]: 'self', [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'Service', operations: { [OperationType.CREATE]: 'self', [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ServiceCall', operations: { [OperationType.CREATE]: 'self', [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'ServiceCallTicket', childOf: 'ServiceCall', subname: 'Tickets', parentIdField: 'serviceCallID', operations: { [OperationType.CREATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'parent', [OperationType.COUNT]: 'self' } },
	{ name: 'ServiceCallTicketResource', childOf: 'ServiceCallTicket', subname: 'Resources', parentIdField: 'serviceCallTicketID', operations: { [OperationType.CREATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'parent', [OperationType.COUNT]: 'self' } },
	{ name: 'ServiceCallTask', childOf: 'ServiceCall', subname: 'Tasks', parentIdField: 'serviceCallID', operations: { [OperationType.CREATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'parent', [OperationType.COUNT]: 'self' } },
	{ name: 'ServiceCallTaskResource', childOf: 'ServiceCallTask', subname: 'Resources', parentIdField: 'serviceCallTaskID', operations: { [OperationType.CREATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'parent', [OperationType.COUNT]: 'self' } },
	// Skills entity (read-only)
	{ name: 'Skill', operations: { [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'Survey', operations: { [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'SurveyResults', operations: { [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'Task', childOf: 'Project', subname: 'task', parentIdField: 'projectID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'parent', [OperationType.COUNT]: 'self' } },
	{ name: 'TaskNote', childOf: 'Task', subname: 'Note', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.DELETE]: 'parent' } },
	// Tickets entity
	{ name: 'Ticket', operations: { [OperationType.CREATE]: 'self', [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self', [OperationType.READ]: 'self' }, hasUserDefinedFields: true, supportsWebhookCallouts: true },
	{ name: 'TicketWebhook', childOf: 'Ticket', subname: 'Webhook', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.DELETE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'TicketWebhookExcludedResource', childOf: 'TicketWebhook', subname: 'ExcludedResource', parentChain: ['Ticket', 'TicketWebhook'], operations: { [OperationType.CREATE]: 'parent', [OperationType.DELETE]: 'parent' } },
	{ name: 'TicketWebhookField', childOf: 'TicketWebhook', subname: 'Field', parentChain: ['Ticket', 'TicketWebhook'], operations: { [OperationType.CREATE]: 'parent', [OperationType.DELETE]: 'parent' } },
	{ name: 'TicketWebhookUdfField', childOf: 'TicketWebhook', subname: 'UdfField', parentChain: ['Ticket', 'TicketWebhook'], operations: { [OperationType.CREATE]: 'parent', [OperationType.DELETE]: 'parent' } },
	{ name: 'TicketNote', childOf: 'Ticket', subname: 'Notes', parentIdField: 'ticketID', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' }, supportsWebhookCallouts: true },
	{ name: 'TicketNoteWebhook', childOf: 'TicketNote', subname: 'Webhook', operations: { [OperationType.CREATE]: 'parent', [OperationType.UPDATE]: 'parent', [OperationType.DELETE]: 'parent', [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'TicketNoteWebhookExcludedResource', childOf: 'TicketNoteWebhook', subname: 'ExcludedResource', parentChain: ['Ticket', 'TicketNote', 'TicketNoteWebhook'], operations: { [OperationType.CREATE]: 'parent', [OperationType.DELETE]: 'parent' } },
	{ name: 'TicketNoteWebhookField', childOf: 'TicketNoteWebhook', subname: 'Field', parentChain: ['Ticket', 'TicketNote', 'TicketNoteWebhook'], operations: { [OperationType.CREATE]: 'parent', [OperationType.DELETE]: 'parent' } },
	{ name: 'TicketNoteWebhookUdfField', childOf: 'TicketNoteWebhook', subname: 'UdfField', parentChain: ['Ticket', 'TicketNote', 'TicketNoteWebhook'], operations: { [OperationType.CREATE]: 'parent', [OperationType.DELETE]: 'parent' } },
	// TicketHistory entity (read-only)
	{ name: 'TicketHistory', operations: { [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self', [OperationType.READ]: 'self' }, noPluralize: true },
	{ name: 'Subscription', operations: { [OperationType.CREATE]: 'self', [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'self', [OperationType.COUNT]: 'self' } },
	{ name: 'SubscriptionPeriod', operations: { [OperationType.QUERY]: 'self', [OperationType.COUNT]: 'self' } },
	// TimeEntry entity and its attachment
	{ name: 'TimeEntry', operations: { [OperationType.CREATE]: 'self', [OperationType.UPDATE]: 'self', [OperationType.QUERY]: 'self', [OperationType.DELETE]: 'self', [OperationType.COUNT]: 'self' }, hasUserDefinedFields: true },
	{ name: 'TimeEntryAttachment', childOf: 'TimeEntry', subname: 'Attachment', isAttachment: true, operations: { [OperationType.CREATE]: 'parent', [OperationType.DELETE]: 'parent' } },
];

/**
 * Case-insensitive lookup of entity metadata by name. Returns undefined if entity not found.
 * @param name - The entity name to look up (e.g. 'billingcode', 'BillingCode', or 'BILLINGCODE')
 */
export function getEntityMetadata(name: string): IEntityMetadata | undefined {
	return AUTOTASK_ENTITIES.find(e => e.name.toLowerCase() === name.toLowerCase());
}
